import fs from 'node:fs';
const source=fs.readFileSync('worker/concept-factory-v2.js','utf8');
if(!source.includes("IMAGE_PIPELINE_VERSION='ai-image-v3-atomic-preview'")) throw new Error('Atomic preview deployer must remain the canonical concept deployment pipeline.');
if(source.includes("vercelUploadFile(env,'vercel.json'")) throw new Error('Concept deployments must not upload vercel.json or install catch-all rewrites.');
if(source.includes("target:'production'")) throw new Error('Concept candidates must never deploy directly to the Vercel production target before verification.');
if(!source.includes('/v6/deployments/${encodeURIComponent(deploymentId)}/files')) throw new Error('Verification must inspect the Vercel deployment file tree.');
if(!source.includes('/v8/deployments/${encodeURIComponent(deploymentId)}/files/${encodeURIComponent(fileId)}')) throw new Error('Verification must read exact deployment file contents through the Vercel API.');
if(!source.includes('sha!==ref.sha')) throw new Error('Deployment source files must match the uploaded content digests exactly.');
if(!source.includes('function isWebp(bytes)')) throw new Error('Live verification must inspect WebP file signatures.');
if(!source.includes('verifyLiveAlias(alias,buildId)')) throw new Error('The final customer-facing alias must be verified after activation.');
if(!source.includes('manifest build_id mismatch')) throw new Error('Live manifest verification must bind the alias to the current build ID.');
if(!source.includes("routing:'native_static_preview_then_alias'")) throw new Error('Concept manifests must record preview-then-alias routing semantics.');
if(!(source.indexOf('await verifySourceFiles(env,deploymentId,fileRefs)')<source.indexOf('await assignAlias(env,deploymentId,alias)'))) throw new Error('Exact source verification must happen before alias activation.');
if(!(source.indexOf('await assignAlias(env,deploymentId,alias)')<source.indexOf('await verifyLiveAlias(alias,buildId)'))) throw new Error('Customer-facing verification must happen immediately after alias activation.');
if(!source.includes("concept_state=CASE WHEN COALESCE(concept_url,'')<>'' THEN 'Built' ELSE 'Build Failed' END")) throw new Error('Failed rebuilds must preserve Built state when an existing concept remains available.');
console.log('Concept verification invariants passed.');
