import fs from 'node:fs';
const source=fs.readFileSync('worker/concept-factory-v2.js','utf8');
if(!source.includes("IMAGE_PIPELINE_VERSION='ai-image-v2-static'")) throw new Error('Static v2 deployer must remain the canonical concept deployment pipeline.');
if(source.includes("vercelUploadFile(env,'vercel.json'")) throw new Error('Static concept deployments must not upload vercel.json or install catch-all rewrites.');
if(source.includes("handle:'filesystem'")) throw new Error('Static concept deployments must not depend on custom Vercel route ordering.');
if(!source.includes('/v6/deployments/${encodeURIComponent(deploymentId)}/files')) throw new Error('Verification must confirm the deployment file manifest before public route checks.');
if(!source.includes("['index.html','concept-manifest.json','hero.webp','secondary.webp']")) throw new Error('All canonical static files must be required in the Vercel deployment manifest.');
if(!source.includes('function isWebp(bytes)')) throw new Error('Deployment verification must inspect WebP file signatures.');
if(!source.includes('new Uint8Array(await r.arrayBuffer())')) throw new Error('Deployment verification must inspect deployed asset bytes.');
if(!source.includes('fetchRetry')) throw new Error('Public deployment verification must tolerate Vercel edge propagation delay.');
if(!source.includes('manifest build_id mismatch')) throw new Error('Manifest verification must bind the deployed manifest to the current build ID.');
if(!source.includes("routing:'native_static_no_rewrites'")) throw new Error('Concept manifests must record native static routing semantics.');
if(!source.includes("await verifyDeployment(env,deploymentId,baseUrl,html,buildId)")) throw new Error('Deployment verification must run before activation.');
if(!(source.indexOf('await verifyDeployment(env,deploymentId,baseUrl,html,buildId)')<source.indexOf('await assignAlias(env,deploymentId,alias)'))) throw new Error('Alias activation must occur only after deployment verification.');
console.log('Concept verification invariants passed.');
