import conceptWorker from './concept-factory.js';

const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const clean=(value,max=2000)=>String(value??'').trim().slice(0,max);
const LAUNCH_FEE_CENTS=49900;

function sameOriginMutation(request){const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).host===new URL(request.url).host}catch{return false}}

async function stripeRequest(env,path,{method='GET',params=null}={}){
  if(!env.STRIPE_SECRET_KEY)throw new Error('STRIPE_SECRET_KEY is not configured');
  const init={method,headers:{authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,'stripe-version':'2024-06-20'}};
  let url=`https://api.stripe.com/v1${path}`;
  if(params){const body=new URLSearchParams();for(const [k,v] of Object.entries(params)){if(v===undefined||v===null||v==='')continue;body.append(k,String(v))}if(method==='GET')url+=`?${body}`;else{init.headers['content-type']='application/x-www-form-urlencoded';init.body=body.toString()}}
  const response=await fetch(url,init),text=await response.text();let payload={};try{payload=text?JSON.parse(text):{}}catch{payload={raw:text}}if(!response.ok)throw new Error(payload?.error?.message||`Stripe request failed (${response.status})`);return payload;
}

async function ensureConversionSchema(env){
  if(!env.DB)return;
  const alters=['ALTER TABLE prospects ADD COLUMN customer_id INTEGER','ALTER TABLE prospects ADD COLUMN converted_at TEXT','ALTER TABLE prospects ADD COLUMN checkout_started_at TEXT','ALTER TABLE customers ADD COLUMN source_prospect_id INTEGER','ALTER TABLE customers ADD COLUMN billing_status TEXT','ALTER TABLE customers ADD COLUMN subscription_status TEXT','ALTER TABLE customers ADD COLUMN payment_issue_previous_status TEXT','ALTER TABLE customers ADD COLUMN last_payment_failed_at TEXT','ALTER TABLE customers ADD COLUMN last_payment_recovered_at TEXT','ALTER TABLE customers ADD COLUMN last_refund_at TEXT','ALTER TABLE customers ADD COLUMN launch_invoice_id TEXT','ALTER TABLE customers ADD COLUMN approved_concept_build_id TEXT','ALTER TABLE customers ADD COLUMN approved_concept_deployment_id TEXT'];
  for(const sql of alters){try{await env.DB.prepare(sql).run()}catch(error){if(!/duplicate column|already exists/i.test(String(error?.message||error)))throw error}}
  await env.DB.prepare('CREATE UNIQUE INDEX IF NOT EXISTS idx_prospects_customer_id ON prospects(customer_id) WHERE customer_id IS NOT NULL').run();
  await env.DB.prepare('CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_source_prospect ON customers(source_prospect_id) WHERE source_prospect_id IS NOT NULL').run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_sites (customer_id INTEGER PRIMARY KEY,domain TEXT,preview_url TEXT,production_url TEXT,template_key TEXT,internal_notes TEXT,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
  await env.DB.prepare(`CREATE TABLE IF NOT EXISTS admin_activity (id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,event_type TEXT NOT NULL,description TEXT NOT NULL,metadata_json TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`).run();
}

async function currentUser(request,env){const url=new URL(request.url),headers=new Headers(),cookie=request.headers.get('cookie');if(cookie)headers.set('cookie',cookie);const response=await conceptWorker.fetch(new Request(new URL('/api/admin/me',url.origin),{method:'GET',headers}),env);if(!response.ok)return null;return(await response.json().catch(()=>null))?.user||null}
async function recordActivity(env,customerId,eventType,description,metadata={}){try{await env.DB.prepare(`INSERT INTO admin_activity (customer_id,event_type,description,metadata_json,created_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP)`).bind(customerId||null,clean(eventType,80),clean(description,1000),JSON.stringify(metadata)).run()}catch(error){console.warn('Conversion activity logging unavailable',error instanceof Error?error.message:String(error))}}

async function insertConvertedCustomer(env,prospect){
  const businessName=clean(prospect.business_name,160),customerName=clean(prospect.contact_name,120),email=clean(prospect.email,254).toLowerCase();
  const sql=`INSERT INTO customers (stripe_customer_id,stripe_checkout_session_id,stripe_subscription_id,payment_link_id,customer_name,business_name,email,status,onboarding_completed,welcome_email_sent,source_prospect_id,billing_status,subscription_status,approved_concept_build_id,approved_concept_deployment_id,created_at,updated_at) VALUES (NULL,?,NULL,NULL,?,?,?,'Active Customer',0,0,?,'Pending Launch Invoice','Pending Setup',?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;
  const binds=[null,customerName||null,businessName,email||null,prospect.id,clean(prospect.concept_build_id,255)||null,clean(prospect.concept_deployment_id,255)||null];
  try{const result=await env.DB.prepare(sql).bind(...binds).run();return Number(result.meta?.last_row_id||0)}catch(error){if(!/NOT NULL constraint failed:\s*customers\.stripe_checkout_session_id/i.test(String(error?.message||error)))throw error;binds[0]=`direct_conversion_${prospect.id}_${crypto.randomUUID()}`;const result=await env.DB.prepare(sql).bind(...binds).run();return Number(result.meta?.last_row_id||0)}
}

async function promoteConceptSite(env,customerId,prospect){
  const conceptUrl=clean(prospect.concept_url,1000);if(!conceptUrl)throw new Error('Prospect must have a concept site before conversion.');
  const templateKey=clean(prospect.concept_visual_family||prospect.visual_family||'',120)||null,note=`Approved prospect #${prospect.id} concept promoted unchanged to the active customer site.`;
  let domain=null;try{domain=new URL(conceptUrl).hostname}catch{}
  await env.DB.prepare(`INSERT INTO customer_sites (customer_id,domain,preview_url,production_url,template_key,internal_notes,updated_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(customer_id) DO UPDATE SET domain=COALESCE(customer_sites.domain,excluded.domain),preview_url=excluded.preview_url,production_url=excluded.production_url,template_key=COALESCE(customer_sites.template_key,excluded.template_key),internal_notes=CASE WHEN COALESCE(customer_sites.internal_notes,'')='' THEN excluded.internal_notes ELSE customer_sites.internal_notes || '\n' || excluded.internal_notes END,updated_at=CURRENT_TIMESTAMP`).bind(customerId,domain,conceptUrl,conceptUrl,templateKey,note).run();
}

async function ensureStripeCustomer(env,customerId,prospect){
  const existing=await env.DB.prepare('SELECT stripe_customer_id,email,business_name FROM customers WHERE id=?').bind(customerId).first();if(existing?.stripe_customer_id)return existing.stripe_customer_id;
  const email=clean(prospect.email,254).toLowerCase();if(!email)throw new Error('A customer email is required to send the launch invoice.');
  const created=await stripeRequest(env,'/customers',{method:'POST',params:{email,name:clean(prospect.business_name,160),'metadata[cajunsites_customer_id]':customerId,'metadata[source_prospect_id]':prospect.id}});
  await env.DB.prepare('UPDATE customers SET stripe_customer_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(created.id,customerId).run();return created.id;
}

async function sendLaunchInvoice(env,customerId,prospect){
  const current=await env.DB.prepare('SELECT launch_invoice_id FROM customers WHERE id=?').bind(customerId).first();if(current?.launch_invoice_id)return{invoice_id:current.launch_invoice_id,already_created:true};
  const stripeCustomerId=await ensureStripeCustomer(env,customerId,prospect);
  let invoice=await stripeRequest(env,'/invoices',{method:'POST',params:{customer:stripeCustomerId,collection_method:'send_invoice',days_until_due:14,description:'CajunSites Website Design & Launch','metadata[cajunsites_customer_id]':customerId,'metadata[source_prospect_id]':prospect.id,'metadata[fee_type]':'website_design_launch'}});
  await stripeRequest(env,'/invoiceitems',{method:'POST',params:{customer:stripeCustomerId,invoice:invoice.id,amount:LAUNCH_FEE_CENTS,currency:'usd',description:'Website Design & Launch'}});
  invoice=await stripeRequest(env,`/invoices/${encodeURIComponent(invoice.id)}/finalize`,{method:'POST'});invoice=await stripeRequest(env,`/invoices/${encodeURIComponent(invoice.id)}/send`,{method:'POST'});
  await env.DB.prepare(`UPDATE customers SET launch_invoice_id=?,billing_status='Launch Invoice Sent',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(invoice.id,customerId).run();
  return{invoice_id:invoice.id,hosted_invoice_url:invoice.hosted_invoice_url||null,status:invoice.status||'open'};
}

async function convertProspectToCustomer(request,env,prospectId){
  if(!env.DB)return json({ok:false,error:'Customer database is not configured.'},503);if(!sameOriginMutation(request))return json({ok:false,error:'Invalid request origin.'},403);
  const user=await currentUser(request,env);if(!user)return json({ok:false,error:'Authentication required.'},401);if(user.role==='read_only')return json({ok:false,error:'Your role is read only.'},403);
  await ensureConversionSchema(env);const prospect=await env.DB.prepare('SELECT * FROM prospects WHERE id=? LIMIT 1').bind(prospectId).first();if(!prospect)return json({ok:false,error:'Prospect not found.'},404);
  if(prospect.customer_id)return json({ok:true,already_converted:true,customer_id:Number(prospect.customer_id),customer_url:`/admin/?customer=${Number(prospect.customer_id)}`});
  if(!clean(prospect.concept_url,1000)||prospect.concept_state!=='Built')return json({ok:false,error:'A successfully built concept must be approved before conversion.'},409);
  if(!clean(prospect.concept_deployment_id,255))return json({ok:false,error:'The approved concept deployment could not be identified. Rebuild or verify the concept before conversion.'},409);

  const existing=await env.DB.prepare('SELECT id FROM customers WHERE source_prospect_id=? LIMIT 1').bind(prospect.id).first();let customerId=Number(existing?.id||0);if(!customerId)customerId=await insertConvertedCustomer(env,prospect);if(!customerId)throw new Error('Customer record could not be created.');
  await promoteConceptSite(env,customerId,prospect);
  await env.DB.prepare(`UPDATE prospects SET customer_id=?,stage='Won',outcome='Converted to customer',converted_at=COALESCE(converted_at,CURRENT_TIMESTAMP),checkout_started_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(customerId,prospect.id).run();
  if(clean(prospect.notes,4000)){try{await env.DB.prepare(`INSERT INTO customer_notes (customer_id,note,created_at) VALUES (?,?,CURRENT_TIMESTAMP)`).bind(customerId,`Sales notes carried forward from prospect:\n${clean(prospect.notes,4000)}`).run()}catch(error){console.warn('Could not carry prospect notes into customer record',error instanceof Error?error.message:String(error))}}

  let billing={sent:false};try{billing={sent:true,...await sendLaunchInvoice(env,customerId,prospect)};await recordActivity(env,customerId,'launch_invoice_sent',`${prospect.business_name} Website Design & Launch invoice sent`,billing)}catch(error){const message=clean(error?.message||error,500);await env.DB.prepare(`UPDATE customers SET billing_status='Launch Invoice Error',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(customerId).run();billing={sent:false,error:message};await recordActivity(env,customerId,'launch_invoice_failed',`${prospect.business_name} converted successfully but launch invoice needs attention`,{error:message})}
  await recordActivity(env,customerId,'prospect_converted',`${prospect.business_name} approved concept promoted to active customer site`,{prospect_id:prospect.id,customer_id:customerId,production_url:prospect.concept_url,approved_build_id:prospect.concept_build_id,approved_deployment_id:prospect.concept_deployment_id,billing,actor:{id:user.id,name:user.name,email:user.email,role:user.role}});
  return json({ok:true,customer_id:customerId,prospect_id:prospect.id,production_url:prospect.concept_url,customer_url:`/admin/?customer=${customerId}`,site_status:'Active',billing});
}

async function findCustomerForStripeObject(env,obj){const stripeCustomer=typeof obj?.customer==='string'?obj.customer:obj?.customer?.id;const subscription=typeof obj?.subscription==='string'?obj.subscription:obj?.subscription?.id||(obj?.object==='subscription'?obj.id:null);if(subscription){const row=await env.DB.prepare('SELECT * FROM customers WHERE stripe_subscription_id=? LIMIT 1').bind(subscription).first();if(row)return row}if(stripeCustomer)return env.DB.prepare('SELECT * FROM customers WHERE stripe_customer_id=? ORDER BY id DESC LIMIT 1').bind(stripeCustomer).first();return null}
async function markPaymentIssue(env,customer,reason,subscriptionStatus=null){if(!customer)return;await env.DB.prepare(`UPDATE customers SET payment_issue_previous_status=CASE WHEN status<>'Payment Issue' THEN status ELSE payment_issue_previous_status END,status='Payment Issue',billing_status=?,subscription_status=COALESCE(?,subscription_status),last_payment_failed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(reason,subscriptionStatus,customer.id).run();await recordActivity(env,customer.id,'billing_payment_failed',`${customer.business_name||customer.email} has a Stripe payment issue`,{billing_status:reason,subscription_status:subscriptionStatus,actor:{name:'Stripe webhook',role:'system'}})}
async function markPaymentRecovered(env,customer,subscriptionStatus=null){if(!customer)return;const restore=customer.status==='Payment Issue'?(customer.payment_issue_previous_status||'Active Customer'):customer.status;await env.DB.prepare(`UPDATE customers SET status=?,payment_issue_previous_status=NULL,billing_status='Current',subscription_status=COALESCE(?,subscription_status),last_payment_recovered_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(restore,subscriptionStatus,customer.id).run();await recordActivity(env,customer.id,'billing_payment_recovered',`${customer.business_name||customer.email} payment status recovered`,{restored_status:restore,subscription_status:subscriptionStatus,actor:{name:'Stripe webhook',role:'system'}})}
async function synchronizeStripeLifecycle(event,env){if(!env.DB)return;await ensureConversionSchema(env);const type=event?.type||'',obj=event?.data?.object||{};if(!['invoice.payment_failed','invoice.paid','invoice.payment_succeeded','customer.subscription.updated','customer.subscription.deleted','charge.refunded'].includes(type))return;const customer=await findCustomerForStripeObject(env,obj);if(!customer){console.warn('Stripe lifecycle event did not match a CajunSites customer',{type,id:obj?.id||null});return}if(type==='invoice.payment_failed')return markPaymentIssue(env,customer,'Payment Failed');if(type==='invoice.paid'||type==='invoice.payment_succeeded')return markPaymentRecovered(env,customer,customer.subscription_status);if(type==='customer.subscription.deleted'){await env.DB.prepare(`UPDATE customers SET status='Cancelled',billing_status='Cancelled',subscription_status='canceled',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(customer.id).run();return recordActivity(env,customer.id,'subscription_cancelled',`${customer.business_name||customer.email} subscription was cancelled in Stripe`,{subscription_id:obj.id,actor:{name:'Stripe webhook',role:'system'}})}if(type==='customer.subscription.updated'){const status=clean(obj.status,50)||'unknown';await env.DB.prepare('UPDATE customers SET subscription_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(status,customer.id).run();if(['past_due','unpaid','incomplete_expired','paused'].includes(status))return markPaymentIssue(env,{...customer,subscription_status:status},`Subscription ${status}`,status);if(['active','trialing'].includes(status)&&customer.status==='Payment Issue')return markPaymentRecovered(env,customer,status);return}if(type==='charge.refunded'){await env.DB.prepare(`UPDATE customers SET last_refund_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(customer.id).run();return recordActivity(env,customer.id,'payment_refunded',`${customer.business_name||customer.email} received a Stripe refund`,{charge_id:obj.id,amount_refunded:obj.amount_refunded||null,refunded:Boolean(obj.refunded),actor:{name:'Stripe webhook',role:'system'}})}}

export default{async fetch(request,env){const url=new URL(request.url),conversionMatch=url.pathname.match(/^\/api\/admin\/prospects\/(\d+)\/(?:convert|convert-checkout)$/);if(conversionMatch){if(request.method!=='POST')return json({ok:false,error:'Method not allowed.'},405);try{return await convertProspectToCustomer(request,env,Number(conversionMatch[1]))}catch(error){console.error('Prospect conversion failed',error);return json({ok:false,error:'Could not convert prospect to customer.'},500)}}if(url.pathname==='/api/stripe-webhook'&&request.method==='POST'){const copy=request.clone(),rawBodyPromise=copy.text(),response=await conceptWorker.fetch(request,env);if(!response.ok)return response;try{const event=JSON.parse(await rawBodyPromise);await synchronizeStripeLifecycle(event,env)}catch(error){console.error('Post-verification Stripe synchronization failed',error);return json({ok:false,error:'Webhook synchronization failed.'},500)}return response}if(url.pathname.startsWith('/api/admin/prospects')){try{await ensureConversionSchema(env)}catch(error){console.error('Conversion schema setup failed',error)}}return conceptWorker.fetch(request,env)}};
