import baseWorker from './reliability-hotfix.js';

const ADMIN_COOKIE='cajunsites_admin';
const MAX_FILE_BYTES=10*1024*1024;
const ALLOWED_TYPES=new Set(['image/jpeg','image/png','image/webp']);
const ROLES=new Set(['logo','hero','secondary','gallery','team','general']);
const STATUSES=new Set(['pending','approved','rejected']);
const clean=(v,max=2000)=>String(v??'').trim().slice(0,max);
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const hex=bytes=>Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');
const safeName=name=>clean(name,180).replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'image';
function cookie(request,name){for(const part of (request.headers.get('cookie')||'').split(';')){const [key,...rest]=part.trim().split('=');if(key===name)return decodeURIComponent(rest.join('='))}return ''}
async function sha256(value){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value))))}
async function hmac(value,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))}
function equal(a,b){a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
function sameOrigin(request){const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).host===new URL(request.url).host}catch{return false}}
async function ensureSchema(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_assets (
 id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER NOT NULL, object_key TEXT NOT NULL UNIQUE,
 file_name TEXT NOT NULL, content_type TEXT NOT NULL, size_bytes INTEGER NOT NULL,
 role TEXT NOT NULL DEFAULT 'general', alt_text TEXT, approval_status TEXT NOT NULL DEFAULT 'pending',
 source TEXT NOT NULL DEFAULT 'admin', created_by INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE)`).run();
 await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_customer_assets_customer ON customer_assets(customer_id,created_at DESC)').run();
 await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_customer_assets_build_selection ON customer_assets(customer_id,approval_status,role,created_at DESC)').run()}
async function adminUser(request,env){const token=cookie(request,ADMIN_COOKIE);if(!token)return null;const tokenHash=await sha256(token);return env.DB.prepare(`SELECT u.id,u.email,u.name,u.role FROM admin_sessions s JOIN internal_users u ON u.id=s.user_id WHERE s.token_hash=? AND u.is_active=1 AND s.expires_at>? LIMIT 1`).bind(tokenHash,new Date().toISOString()).first()}
async function activity(env,customerId,type,description,user,metadata={}){try{await env.DB.prepare('INSERT INTO admin_activity (customer_id,event_type,description,metadata_json,created_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP)').bind(customerId,type,description,JSON.stringify({...metadata,actor:user?{id:user.id,name:user.name,email:user.email,role:user.role}:{name:'Customer'}})).run()}catch{}}
async function customerFromToken(env,session,token){if(!env.STRIPE_WEBHOOK_SECRET||!session||!token)return null;const expected=await hmac(`cajunsites:onboarding:${session}`,env.STRIPE_WEBHOOK_SECRET);if(!equal(token,expected))return null;return env.DB.prepare('SELECT id,business_name,email FROM customers WHERE stripe_checkout_session_id=? LIMIT 1').bind(session).first()}
async function verifyImage(file){if(!(file instanceof File))throw new Error('Choose an image file.');if(!ALLOWED_TYPES.has(file.type))throw new Error('Use a JPG, PNG, or WebP image.');if(file.size<1||file.size>MAX_FILE_BYTES)throw new Error('Each image must be 10 MB or smaller.');const h=new Uint8Array(await file.slice(0,16).arrayBuffer());const jpeg=h[0]===0xff&&h[1]===0xd8&&h[2]===0xff;const png=h[0]===0x89&&h[1]===0x50&&h[2]===0x4e&&h[3]===0x47;const webp=h[0]===0x52&&h[1]===0x49&&h[2]===0x46&&h[3]===0x46&&h[8]===0x57&&h[9]===0x45&&h[10]===0x42&&h[11]===0x50;if((file.type==='image/jpeg'&&!jpeg)||(file.type==='image/png'&&!png)||(file.type==='image/webp'&&!webp))throw new Error('The file content does not match its image type.')}
async function upload(env,customer,user,form,source){if(!env.CUSTOMER_ASSETS)return json({ok:false,error:'Customer photo storage is not configured.'},503);const file=form.get('file');try{await verifyImage(file)}catch(error){return json({ok:false,error:error.message},400)}const role=ROLES.has(clean(form.get('role'),30))?clean(form.get('role'),30):'general';const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp';const key=`customers/${customer.id}/${crypto.randomUUID()}-${safeName(file.name).replace(/\.[^.]+$/,'')}.${ext}`;await env.CUSTOMER_ASSETS.put(key,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{customer_id:String(customer.id),source}});const result=await env.DB.prepare(`INSERT INTO customer_assets (customer_id,object_key,file_name,content_type,size_bytes,role,alt_text,approval_status,source,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'pending',?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(customer.id,key,safeName(file.name),file.type,file.size,role,clean(form.get('alt_text'),300)||null,source,user?.id||null).run();await activity(env,customer.id,'customer_asset_uploaded',`${source==='customer'?'Customer':user.name} uploaded ${safeName(file.name)}`,user,{role,size_bytes:file.size});return json({ok:true,id:result.meta?.last_row_id,status:'pending'})}
async function handleAdmin(request,env,url){const user=await adminUser(request,env);if(!user)return json({ok:false,error:'Authentication required.'},401);if(!['owner','admin','operator'].includes(user.role)&&request.method!=='GET')return json({ok:false,error:'This account cannot change customer assets.'},403);if(!sameOrigin(request))return json({ok:false,error:'Invalid request origin.'},403);let match=url.pathname.match(/^\/api\/admin\/customers\/(\d+)\/assets$/);if(match){const customerId=Number(match[1]),customer=await env.DB.prepare('SELECT id,business_name,email FROM customers WHERE id=? LIMIT 1').bind(customerId).first();if(!customer)return json({ok:false,error:'Customer not found.'},404);if(request.method==='GET'){const result=await env.DB.prepare('SELECT id,customer_id,file_name,content_type,size_bytes,role,alt_text,approval_status,source,created_at,updated_at FROM customer_assets WHERE customer_id=? ORDER BY created_at DESC,id DESC').bind(customerId).all();return json({ok:true,assets:result.results||[]})}if(request.method==='POST')return upload(env,customer,user,await request.formData(),'admin');return json({ok:false,error:'Method not allowed.'},405)}
 match=url.pathname.match(/^\/api\/admin\/customer-assets\/(\d+)(?:\/content)?$/);if(!match)return null;const id=Number(match[1]),asset=await env.DB.prepare('SELECT * FROM customer_assets WHERE id=? LIMIT 1').bind(id).first();if(!asset)return json({ok:false,error:'Asset not found.'},404);
 if(url.pathname.endsWith('/content')){if(request.method!=='GET')return json({ok:false,error:'Method not allowed.'},405);const object=await env.CUSTOMER_ASSETS?.get(asset.object_key);if(!object)return json({ok:false,error:'Asset file not found.'},404);return new Response(object.body,{headers:{'content-type':asset.content_type,'content-length':String(asset.size_bytes),'cache-control':'private, max-age=300','x-content-type-options':'nosniff','content-security-policy':"default-src 'none'; img-src 'self'; sandbox"}})}
 if(request.method==='PATCH'){const body=await request.json().catch(()=>({}));const role=ROLES.has(clean(body.role,30))?clean(body.role,30):asset.role,status=STATUSES.has(clean(body.approval_status,30))?clean(body.approval_status,30):asset.approval_status,alt=clean(body.alt_text,300)||null;await env.DB.prepare('UPDATE customer_assets SET role=?,alt_text=?,approval_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(role,alt,status,id).run();await activity(env,asset.customer_id,'customer_asset_updated',`${user.name} updated ${asset.file_name}`,user,{role,approval_status:status});return json({ok:true})}
 if(request.method==='DELETE'){await env.CUSTOMER_ASSETS?.delete(asset.object_key);await env.DB.prepare('DELETE FROM customer_assets WHERE id=?').bind(id).run();await activity(env,asset.customer_id,'customer_asset_deleted',`${user.name} removed ${asset.file_name}`,user);return json({ok:true})}
 return json({ok:false,error:'Method not allowed.'},405)}
async function handleCustomerUpload(request,env){if(request.method!=='POST')return json({ok:false,error:'Method not allowed.'},405);if(!sameOrigin(request))return json({ok:false,error:'Invalid request origin.'},403);const form=await request.formData();const customer=await customerFromToken(env,clean(form.get('checkout_session_id'),255),clean(form.get('onboarding_token'),128));if(!customer)return json({ok:false,error:'This onboarding link is invalid.'},403);return upload(env,customer,null,form,'customer')}

const SECTION_TYPES=new Set(['hero','services','about','trust','process','gallery','reviews','contact','cta','custom']);
const slugify=value=>clean(value,80).toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'page';
const parse=(value,fallback={})=>{try{return value?JSON.parse(value):fallback}catch{return fallback}};
function normalizeItems(value){return Array.isArray(value)?value.map(item=>({title:clean(item?.title||item,120),body:clean(item?.body,500)})).filter(item=>item.title).slice(0,12):[]}
function normalizeSection(value,index){const type=SECTION_TYPES.has(clean(value?.type,30))?clean(value.type,30):'custom';return{id:clean(value?.id,80)||crypto.randomUUID(),type,visible:value?.visible!==false,eyebrow:clean(value?.eyebrow,80),heading:clean(value?.heading,180),body:clean(value?.body,2000),items:normalizeItems(value?.items),cta_label:clean(value?.cta_label,70),cta_href:clean(value?.cta_href,500),order:index}}
function normalizeContent(value,customer){
 const input=value&&typeof value==='object'?value:{};
 const pages=(Array.isArray(input.pages)?input.pages:[]).slice(0,5).map((page,pageIndex)=>{const title=clean(page?.title,100)||`Page ${pageIndex+1}`,slug=pageIndex===0?'':slugify(page?.slug||title);return{id:clean(page?.id,80)||crypto.randomUUID(),title,slug,nav_label:clean(page?.nav_label,40)||title,show_in_nav:page?.show_in_nav!==false,seo_title:clean(page?.seo_title,180),meta_description:clean(page?.meta_description,320),sections:(Array.isArray(page?.sections)?page.sections:[]).slice(0,20).map(normalizeSection)}});
 if(!pages.length)pages.push({id:crypto.randomUUID(),title:'Home',slug:'',nav_label:'Home',show_in_nav:true,seo_title:'',meta_description:'',sections:[normalizeSection({type:'hero',heading:customer.business_name||'Welcome'},0),normalizeSection({type:'services',heading:'Services'},1),normalizeSection({type:'about',heading:`About ${customer.business_name||'Us'}`},2),normalizeSection({type:'contact',heading:'Contact Us'},3)]});
 return{schema_version:'production-content-v1',global:{business_name:clean(input.global?.business_name,160)||clean(customer.business_name,160),phone:clean(input.global?.phone,50)||clean(customer.phone,50),email:clean(input.global?.email,254)||clean(customer.email,254),address:clean(input.global?.address,300)||clean(customer.address,300),hours:clean(input.global?.hours,500),primary_cta:clean(input.global?.primary_cta,70)||'Contact Us'},pages};
}
async function ensureContentSchema(env){
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_site_content (customer_id INTEGER PRIMARY KEY,draft_json TEXT NOT NULL,published_json TEXT,current_version INTEGER NOT NULL DEFAULT 1,updated_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE)`).run();
 await env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_site_content_versions (id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER NOT NULL,version_number INTEGER NOT NULL,content_json TEXT NOT NULL,change_summary TEXT,created_by INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE,UNIQUE(customer_id,version_number))`).run();
}
async function defaultContent(env,customer){
 const prospect=customer.source_prospect_id?await env.DB.prepare('SELECT * FROM prospects WHERE id=? LIMIT 1').bind(customer.source_prospect_id).first():null,research=parse(prospect?.research_json,{}),model=parse(prospect?.concept_design_model_json,research.concept_design_model||research.design_profile||{}),services=(research.services||[]).filter(x=>!x.confidence||x.confidence==='high').map(x=>({title:clean(x.name,120),body:clean(x.description,500)}));
 return normalizeContent({global:{business_name:customer.business_name||prospect?.business_name,phone:prospect?.phone,email:customer.email||prospect?.email,address:prospect?.address,primary_cta:model.cta},pages:[{title:'Home',slug:'',nav_label:'Home',sections:[{type:'hero',eyebrow:research.vertical||prospect?.category,heading:model.headline,body:research.summary,cta_label:model.cta},{type:'services',eyebrow:'What we offer',heading:'Services',body:research.summary,items:services},{type:'about',eyebrow:`About ${customer.business_name||''}`,heading:research.value_proposition||'',body:research.summary},{type:'contact',eyebrow:'Contact & location',heading:`Take the next step with ${customer.business_name||''}`,body:''},{type:'cta',heading:model.cta,cta_label:model.cta}]}]},customer);
}
async function handleContent(request,env,url){
 const match=url.pathname.match(/^\/api\/admin\/customers\/(\d+)\/content$/);if(!match)return null;
 const user=await adminUser(request,env);if(!user)return json({ok:false,error:'Authentication required.'},401);if(!sameOrigin(request))return json({ok:false,error:'Invalid request origin.'},403);if(request.method!=='GET'&&!['owner','admin','operator'].includes(user.role))return json({ok:false,error:'This account cannot edit production content.'},403);
 await ensureContentSchema(env);const customer=await env.DB.prepare('SELECT * FROM customers WHERE id=? LIMIT 1').bind(Number(match[1])).first();if(!customer)return json({ok:false,error:'Customer not found.'},404);let row=await env.DB.prepare('SELECT * FROM customer_site_content WHERE customer_id=? LIMIT 1').bind(customer.id).first();
 if(request.method==='GET'){const content=row?normalizeContent(parse(row.draft_json,{}),customer):await defaultContent(env,customer);return json({ok:true,content,version:row?.current_version||0,saved:Boolean(row)});}
 if(request.method!=='PUT')return json({ok:false,error:'Method not allowed.'},405);const body=await request.json().catch(()=>null);if(!body)return json({ok:false,error:'Invalid content document.'},400);const content=normalizeContent(body.content||body,customer),version=(row?.current_version||0)+1,serialized=JSON.stringify(content),summary=clean(body.change_summary,240)||'Structured content updated';
 const statements=[env.DB.prepare(`INSERT INTO customer_site_content (customer_id,draft_json,current_version,updated_by,created_at,updated_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(customer_id) DO UPDATE SET draft_json=excluded.draft_json,current_version=excluded.current_version,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP`).bind(customer.id,serialized,version,user.id),env.DB.prepare('INSERT INTO customer_site_content_versions (customer_id,version_number,content_json,change_summary,created_by,created_at) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP)').bind(customer.id,version,serialized,summary,user.id),env.DB.prepare('UPDATE customers SET business_name=?,email=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(content.global.business_name,content.global.email||customer.email,customer.id)];
 if(customer.source_prospect_id)statements.push(env.DB.prepare('UPDATE prospects SET business_name=?,phone=?,email=?,address=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(content.global.business_name,content.global.phone||null,content.global.email||null,content.global.address||null,customer.source_prospect_id));await env.DB.batch(statements);
 await activity(env,customer.id,'production_content_saved',`${user.name} saved production website content`,user,{version,summary,pages:content.pages.length});return json({ok:true,content,version});
}
export default{async fetch(request,env,context){const url=new URL(request.url);if(!env.DB)return baseWorker.fetch(request,env,context);const contentResponse=await handleContent(request,env,url);if(contentResponse)return contentResponse;if(url.pathname.startsWith('/api/admin/customer')||url.pathname.match(/^\/api\/admin\/customers\/\d+\/assets$/)){await ensureSchema(env);const response=await handleAdmin(request,env,url);if(response)return response}if(url.pathname==='/api/onboarding/assets'){await ensureSchema(env);return handleCustomerUpload(request,env)}return baseWorker.fetch(request,env,context)}};
