import baseWorker from './stale-build-recovery.js';

const ADMIN_COOKIE='cajunsites_admin';
const MAX_FILE_BYTES=10*1024*1024;
const ALLOWED_TYPES=new Set(['image/jpeg','image/png','image/webp']);
const ROLES=new Set(['logo','hero','secondary','gallery','team','general']);
const STATUSES=new Set(['pending','approved','rejected']);
const clean=(v,max=2000)=>String(v??'').trim().slice(0,max);
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const hex=bytes=>Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');
const safeName=name=>clean(name,180).replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'image';
function cookie(request,name){for(const part of (request.headers.get('cookie')||'').split(';')){const [key,...rest]=part.trim().split('=');if(key===name)return decodeURIComponent(rest.join('='))}return ''}
async function sha256(value){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(value))))}
async function hmac(value,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),'HMAC',{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))}
function equal(a,b){a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0}
function sameOrigin(request){const origin=request.headers.get('origin');if(!origin)return true;try{return new URL(origin).host===new URL(request.url).host}catch{return false}}
async function ensureSchema(env){await env.DB.prepare(`CREATE TABLE IF NOT EXISTS customer_assets (
 id INTEGER PRIMARY KEY AUTOINCREMENT, customer_id INTEGER NOT NULL, object_key TEXT NOT NULL UNIQUE,
 file_name TEXT NOT NULL, content_type TEXT NOT NULL, size_bytes INTEGER NOT NULL,
 role TEXT NOT NULL DEFAULT 'general', alt_text TEXT, approval_status TEXT NOT NULL DEFAULT 'pending',
 source TEXT NOT NULL DEFAULT 'admin', created_by INTEGER, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE CASCADE)`).run();
 await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_customer_assets_customer ON customer_assets(customer_id,created_at DESC)').run();
 await env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_customer_assets_build_selection ON customer_assets(customer_id,approval_status,role,created_at DESC)').run()}
async function adminUser(request,env){const token=cookie(request,ADMIN_COOKIE);if(!token)return null;const tokenHash=await sha256(token);return env.DB.prepare(`SELECT u.id,u.email,u.name,u.role FROM admin_sessions s JOIN internal_users u ON u.id=s.user_id WHERE s.token_hash=? AND u.is_active=1 AND s.expires_at>? LIMIT 1`).bind(tokenHash,new Date().toISOString()).first()}
async function activity(env,customerId,type,description,user,metadata={}){try{await env.DB.prepare('INSERT INTO admin_activity (customer_id,event_type,description,metadata_json,created_at) VALUES (?,?,?,?,CURRENT_TIMESTAMP)').bind(customerId,type,description,JSON.stringify({...metadata,actor:user?{id:user.id,name:user.name,email:user.email,role:user.role}:{name:'Customer'}})).run()}catch{}}
async function customerFromToken(env,session,token){if(!env.STRIPE_WEBHOOK_SECRET||!session||!token)return null;const expected=await hmac(`cajunsites:onboarding:${session}`,env.STRIPE_WEBHOOK_SECRET);if(!equal(token,expected))return null;return env.DB.prepare('SELECT id,business_name,email FROM customers WHERE stripe_checkout_session_id=? LIMIT 1').bind(session).first()}
async function verifyImage(file){if(!(file instanceof File))throw new Error('Choose an image file.');if(!ALLOWED_TYPES.has(file.type))throw new Error('Use a JPG, PNG, or WebP image.');if(file.size<1||file.size>MAX_FILE_BYTES)throw new Error('Each image must be 10 MB or smaller.');const h=new Uint8Array(await file.slice(0,16).arrayBuffer());const jpeg=h[0]===0xff&&h[1]===0xd8&&h[2]===0xff;const png=h[0]===0x89&&h[1]===0x50&&h[2]===0x4e&&h[3]===0x47;const webp=h[0]===0x52&&h[1]===0x49&&h[2]===0x46&&h[3]===0x46&&h[8]===0x57&&h[9]===0x45&&h[10]===0x42&&h[11]===0x50;if((file.type==='image/jpeg'&&!jpeg)||(file.type==='image/png'&&!png)||(file.type==='image/webp'&&!webp))throw new Error('The file content does not match its image type.')}
async function upload(env,customer,user,form,source){if(!env.CUSTOMER_ASSETS)return json({ok:false,error:'Customer photo storage is not configured.'},503);const file=form.get('file');try{await verifyImage(file)}catch(error){return json({ok:false,error:error.message},400)}const role=ROLES.has(clean(form.get('role'),30))?clean(form.get('role'),30):'general';const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp';const key=`customers/${customer.id}/${crypto.randomUUID()}-${safeName(file.name).replace(/\.[^.]+$/,'')}.${ext}`;await env.CUSTOMER_ASSETS.put(key,file.stream(),{httpMetadata:{contentType:file.type},customMetadata:{customer_id:String(customer.id),source}});const result=await env.DB.prepare(`INSERT INTO customer_assets (customer_id,object_key,file_name,content_type,size_bytes,role,alt_text,approval_status,source,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'pending',?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(customer.id,key,safeName(file.name),file.type,file.size,role,clean(form.get('alt_text'),300)||null,source,user?.id||null).run();await activity(env,customer.id,'customer_asset_uploaded',`${source==='customer'?'Customer':user.name} uploaded ${safeName(file.name)}`,user,{role,size_bytes:file.size});return json({ok:true,id:result.meta?.last_row_id,status:'pending'})}
async function handleAdmin(request,env,url){const user=await adminUser(request,env);if(!user)return json({ok:false,error:'Authentication required.'},401);if(!['owner','admin','operator'].includes(user.role)&&request.method!=='GET')return json({ok:false,error:'This account cannot change customer assets.'},403);if(!sameOrigin(request))return json({ok:false,error:'Invalid request origin.'},403);let match=url.pathname.match(/^\/api\/admin\/customers\/(\d+)\/assets$/);if(match){const customerId=Number(match[1]),customer=await env.DB.prepare('SELECT id,business_name,email FROM customers WHERE id=? LIMIT 1').bind(customerId).first();if(!customer)return json({ok:false,error:'Customer not found.'},404);if(request.method==='GET'){const result=await env.DB.prepare('SELECT id,customer_id,file_name,content_type,size_bytes,role,alt_text,approval_status,source,created_at,updated_at FROM customer_assets WHERE customer_id=? ORDER BY created_at DESC,id DESC').bind(customerId).all();return json({ok:true,assets:result.results||[]})}if(request.method==='POST')return upload(env,customer,user,await request.formData(),'admin');return json({ok:false,error:'Method not allowed.'},405)}
 match=url.pathname.match(/^\/api\/admin\/customer-assets\/(\d+)(?:\/content)?$/);if(!match)return null;const id=Number(match[1]),asset=await env.DB.prepare('SELECT * FROM customer_assets WHERE id=? LIMIT 1').bind(id).first();if(!asset)return json({ok:false,error:'Asset not found.'},404);
 if(url.pathname.endsWith('/content')){if(request.method!=='GET')return json({ok:false,error:'Method not allowed.'},405);const object=await env.CUSTOMER_ASSETS?.get(asset.object_key);if(!object)return json({ok:false,error:'Asset file not found.'},404);return new Response(object.body,{headers:{'content-type':asset.content_type,'content-length':String(asset.size_bytes),'cache-control':'private, max-age=300','x-content-type-options':'nosniff','content-security-policy':"default-src 'none'; img-src 'self'; sandbox"}})}
 if(request.method==='PATCH'){const body=await request.json().catch(()=>({}));const role=ROLES.has(clean(body.role,30))?clean(body.role,30):asset.role,status=STATUSES.has(clean(body.approval_status,30))?clean(body.approval_status,30):asset.approval_status,alt=clean(body.alt_text,300)||null;await env.DB.prepare('UPDATE customer_assets SET role=?,alt_text=?,approval_status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(role,alt,status,id).run();await activity(env,asset.customer_id,'customer_asset_updated',`${user.name} updated ${asset.file_name}`,user,{role,approval_status:status});return json({ok:true})}
 if(request.method==='DELETE'){await env.CUSTOMER_ASSETS?.delete(asset.object_key);await env.DB.prepare('DELETE FROM customer_assets WHERE id=?').bind(id).run();await activity(env,asset.customer_id,'customer_asset_deleted',`${user.name} removed ${asset.file_name}`,user);return json({ok:true})}
 return json({ok:false,error:'Method not allowed.'},405)}
async function handleCustomerUpload(request,env){if(request.method!=='POST')return json({ok:false,error:'Method not allowed.'},405);if(!sameOrigin(request))return json({ok:false,error:'Invalid request origin.'},403);const form=await request.formData();const customer=await customerFromToken(env,clean(form.get('checkout_session_id'),255),clean(form.get('onboarding_token'),128));if(!customer)return json({ok:false,error:'This onboarding link is invalid.'},403);return upload(env,customer,null,form,'customer')}
export default{async fetch(request,env,context){const url=new URL(request.url);if(!env.DB)return baseWorker.fetch(request,env,context);if(url.pathname.startsWith('/api/admin/customer')||url.pathname.match(/^\/api\/admin\/customers\/\d+\/assets$/)){await ensureSchema(env);const response=await handleAdmin(request,env,url);if(response)return response}if(url.pathname==='/api/onboarding/assets'){await ensureSchema(env);return handleCustomerUpload(request,env)}return baseWorker.fetch(request,env,context)}};
