import assert from 'node:assert/strict';
import fs from 'node:fs';
import {resolveImagePolicy} from './image-pipeline/policy-resolver.js';
import {buildImageBrief,applyAIImages} from './image-pipeline/ai-image-pipeline.js';

const sidelines={id:1,business_name:'Sidelines Barbershop',category:'Barbershop',research_json:JSON.stringify({vertical:'Automotive Repair',identity_confidence:'high',services:[{name:'Engine Repair',confidence:'high'}],design_profile:{image_theme:'mechanic garage engines',mood:'bold'}}),enrichment_provenance_json:JSON.stringify({category:{origin:'manual'}})};
const sidelinesPolicy=resolveImagePolicy(sidelines);
assert.equal(sidelinesPolicy.policy_id,'beauty.barber','Trusted barbershop identity must beat conflicting research imagery.');
assert.equal(sidelinesPolicy.identity.trusted_family,'barber');
assert.equal(sidelinesPolicy.identity.research_family,'automotive');
assert.equal(sidelinesPolicy.identity.conflict,true,'Conflicting research family must be surfaced.');
const heroBrief=buildImageBrief(sidelines,'hero',sidelinesPolicy);
assert.match(heroBrief.prompt,/trusted business identity \(barber\) controls this image/i);
assert.match(heroBrief.prompt,/mechanic|automotive|engine/i,'Barber policy must explicitly exclude automotive imagery.');
assert.match(heroBrief.prompt,/30 percent negative space/i,'Hero prompt must reserve website copy space.');
assert.match(heroBrief.prompt,/representative only/i,'Generated imagery must remain representative, never actual-work evidence.');

const dentist={business_name:'Example Dental',category:'Dentistry',verified_services_json:JSON.stringify([{name:'Dental Cleaning'}]),enrichment_provenance_json:JSON.stringify({category:{origin:'manual'},verified_services_json:{origin:'manual'}}),research_json:JSON.stringify({vertical:'Dentistry',services:[{name:'Dental Implants',confidence:'high'}]})};
const dentalPolicy=resolveImagePolicy(dentist);
assert.equal(dentalPolicy.policy_id,'healthcare.dentistry');
assert.deepEqual(dentalPolicy.verified_service_names,['Dental Cleaning'],'Manual verified services must override research services.');
assert.ok(dentalPolicy.verified_service_ids.includes('preventive_care'),'Verified cleaning must activate preventive-care overlay.');
assert.ok(!dentalPolicy.verified_service_ids.includes('implants'),'Research-only implant service must not override manually verified services.');

const restaurant={business_name:'Anita\'s Smokin Steak Burgers',category:'Restaurant',research_json:JSON.stringify({vertical:'Burger Restaurant',services:[{name:'Steak Burgers',confidence:'high'}],design_profile:{image_theme:'smoked steak burgers on a grill'}})};
const restaurantPolicy=resolveImagePolicy(restaurant);
assert.equal(restaurantPolicy.policy_id,'food.restaurant','Restaurant prospects must use the restaurant-specific QA policy.');
assert.equal(restaurantPolicy.policy_mode,'specialized');
assert.ok(restaurantPolicy.allowed_image_subjects.some(x=>/burger|grill|food/i.test(x)),'Restaurant policy must retain verified food-specific visual cues.');
assert.ok(restaurantPolicy.thresholds.overall_auto_approve<=80,'Restaurant policy must avoid the overly strict generic threshold that caused repeated valid secondary-image rejection.');
assert.ok(restaurantPolicy.qa_instructions.specialty_checks.some(x=>/secondary image/i.test(x)),'Restaurant QA must explicitly allow a distinct representative secondary composition.');

const nutrition={business_name:'Best Life Nutrition',category:'Nutrition',research_json:JSON.stringify({vertical:'Nutrition & Wellness',identity_confidence:'high',services:[{name:'Nutrition Coaching',confidence:'high'},{name:'Meal Planning',confidence:'high'}],design_profile:{image_theme:'healthy food and supportive nutrition coaching'}})};
const nutritionPolicy=resolveImagePolicy(nutrition);
assert.equal(nutritionPolicy.policy_id,'wellness.nutrition','Nutrition prospects must receive a purpose-built nutrition policy instead of the generic fallback.');
assert.equal(nutritionPolicy.policy_mode,'specialized');
assert.ok(nutritionPolicy.allowed_image_subjects.some(x=>/nutrition|meal|healthy|food/i.test(x)),'Nutrition policy must provide safe business-relevant visual subjects.');
assert.ok(nutritionPolicy.forbidden_image_subjects.some(x=>/before and after|medical|disease/i.test(x)),'Nutrition policy must reject unsupported health-result imagery and medical claims.');

const futureUnknown={business_name:'Bayou Drone Mapping',research_json:JSON.stringify({vertical:'Aerial Mapping & Drone Photography',identity_confidence:'high',services:[{name:'Aerial Property Photography',confidence:'high'},{name:'Drone Mapping',confidence:'high'}],design_profile:{image_theme:'professional aerial mapping and drone photography'}})};
const derivedPolicy=resolveImagePolicy(futureUnknown);
assert.equal(derivedPolicy.policy_mode,'derived','An unknown but well-researched future vertical must receive a prospect-specific derived policy.');
assert.match(derivedPolicy.policy_id,/^derived\./);
assert.ok(derivedPolicy.verified_service_names.includes('Drone Mapping'));
assert.ok(derivedPolicy.hard_reject_rules.some(x=>x.code==='unsupported_service'),'Derived policies must inherit universal hard rejects and cannot invent capabilities.');
assert.ok(derivedPolicy.hard_reject_rules.some(x=>x.code==='fabricated_branding'),'Derived policies must preserve universal branding safeguards.');

const insufficient=resolveImagePolicy({business_name:'Mystery Business',research_json:JSON.stringify({identity_confidence:'high'})});
assert.equal(insufficient.policy_mode,'insufficient-research','A prospect with no useful vertical or service evidence must stop for research review instead of silently using arbitrary imagery.');
assert.equal(insufficient.status,'blocked');

const repairedHtml=applyAIImages('<!doctype html><html><head></head><body><div style="background-image:url(https://old.example/hero.jpg)"></div></body></html>',{hero:'https://old.example/hero.jpg',secondary:'https://old.example/secondary.jpg'},{policy_id:'food.restaurant',hero:{asset_path:'/assets/hero.webp'},secondary:{asset_path:'/assets/secondary.webp'}});
assert.match(repairedHtml,/\/assets\/hero\.webp/,'Applied concept HTML must reference the local hero asset.');
assert.match(repairedHtml,/\/assets\/secondary\.webp/,'Applied concept HTML must reference the local secondary asset even when the renderer omits its legacy source URL.');
assert.match(repairedHtml,/rel="preload" as="image" href="\/assets\/secondary\.webp"/,'Missing optional image references must be repaired before deployment verification.');

const pipeline=fs.readFileSync('worker/image-pipeline/ai-image-pipeline.js','utf8');
const provider=fs.readFileSync('worker/providers/image-generation.js','utf8');
const concept=fs.readFileSync('worker/concept-factory-v2.js','utf8');
const designWorker=fs.readFileSync('worker/concept-design-worker.js','utf8');
const staleRecovery=fs.readFileSync('worker/stale-build-recovery.js','utf8');
const customerAssets=fs.readFileSync('worker/customer-assets.js','utf8');
const reliabilityWorker=fs.readFileSync('worker/reliability-hotfix.js','utf8');
const wrangler=fs.readFileSync('wrangler.jsonc','utf8');
const migration=fs.readFileSync('migrations/0013_ai_image_pipeline.sql','utf8');
assert.match(pipeline,/MAX_ATTEMPTS=3/,'Image generation must cap retries.');
assert.match(pipeline,/Suitable \$\{role\} imagery could not be verified/,'Hero image pipeline must still fail closed after retry exhaustion.');
assert.match(pipeline,/qa_instructions\?\.specialty_checks/,'Policy-specific visual QA instructions must reach the QA model.');
assert.match(pipeline,/thresholdProfile/,'Secondary image QA must use role-appropriate thresholds.');
assert.match(pipeline,/safeSecondaryFallback/,'A safe secondary image that narrowly misses soft thresholds must be recoverable.');
assert.match(pipeline,/approved_hero_reuse/,'Secondary exhaustion must have an explicit last-resort approved-hero fallback instead of failing the entire concept.');
assert.match(pipeline,/degraded_fallback/,'Fallback image decisions must remain observable in image metadata.');
assert.match(pipeline,/rejectionSummary/,'Image failures must retain actionable score and QA diagnostics.');
assert.match(pipeline,/policy_mode==='insufficient-research'/,'Image generation must stop before provider calls when research cannot support a safe visual policy.');
assert.match(pipeline,/policy_mode:policy\.policy_mode/,'Resolved visual policy mode must remain observable in build output.');
assert.match(provider,/gpt-image-2\.5-sunburst/,'Production image provider must preserve the current model default.');
assert.match(provider,/1536x1024/,'Image provider must support landscape concept images.');
assert.match(pipeline,/generateImageAsset/,'Image generation must run through the provider abstraction.');
assert.match(pipeline,/evaluateImageAsset/,'Visual QA must run through the provider abstraction.');
assert.match(pipeline,/provider_usage_events/,'Image provider usage must be observable.');
assert.match(pipeline,/\/assets\/hero\.webp/,'Hero must use a stable deployment-local asset path.');
assert.match(pipeline,/\/assets\/secondary\.webp/,'Secondary must use a stable deployment-local asset path.');
assert.match(pipeline,/ensureLocalAssetReferences/,'Concept packaging must repair missing local image references before verification.');
assert.doesNotMatch(pipeline,/IMAGE_ASSETS|serveImageAsset|storage_key|public_url/,'Image pipeline must not depend on R2 or a separate public image service.');
assert.match(pipeline,/qaResult\?\.approved/,'QA approval must be persisted.');
assert.match(concept,/generateApprovedConceptImages\(env,p,buildId\)/,'Concept builds must bind image metadata to the build ID.');
assert.match(concept,/\/v2\/files/,'Approved deployment files must be uploaded through the Vercel file API.');
assert.match(concept,/x-vercel-digest/,'Vercel file uploads must be content-addressed by digest.');
assert.match(concept,/concept-manifest\.json/,'Each concept deployment must include a manifest.');
assert.match(concept,/verifySourceFiles/,'Concept deployments must verify exact stored deployment bytes before activation.');
assert.ok(concept.indexOf('await verifySourceFiles')<concept.indexOf('await assignAlias'),'Stored deployment verification must happen before alias activation.');
assert.match(concept,/verifyLiveAlias/,'The live alias must be verified after activation before the build is committed.');
assert.ok(concept.indexOf('await assignAlias')<concept.indexOf('await verifyLiveAlias'),'Live alias verification must happen after alias activation.');
assert.doesNotMatch(concept,/vercelUploadFile\(env,'vercel\.json'/,'Atomic preview deployments must not install a catch-all Vercel rewrite.');
assert.match(concept,/\/v6\/deployments\/\$\{encodeURIComponent\(deploymentId\)\}\/files/,'Atomic preview deployments must inspect the Vercel deployment file tree.');
assert.match(concept,/deploymentFileBytes/,'Atomic preview deployments must read exact stored file bytes through the Vercel deployment file API.');
assert.match(concept,/sha1Hex/,'Stored deployment verification must compare content digests.');
assert.match(concept,/env\.DB\.batch/,'Current concept state and deployment metadata must be committed atomically in D1.');
assert.match(concept,/previous_deployment_id/,'Build history must retain the prior deployment for rollback.');
assert.match(concept,/assignAlias\(env,oldDeploymentId,alias\)/,'Alias activation failure after a move must support rollback to the old deployment.');
assert.match(concept,/const customerId=Number\(p\.customer_id\|\|0\)/,'Builds must distinguish converted customers from sales prospects.');
assert.match(concept,/\$\{slug\}-review/,'Converted customer rebuilds must use an isolated production-review alias.');
assert.match(designWorker,/import staticBuildWorker from '\.\/concept-factory-v2\.js'/,'The top-level Concept Design Worker must route builds through the atomic preview deployer.');
assert.match(migration,/concept_builds/,'Canonical migration must retain build history.');
assert.match(migration,/asset_path/,'Canonical image metadata must store deployment-local asset paths.');
assert.match(migration,/concept_build_id/,'Prospects must reference their current concept build.');
assert.doesNotMatch(wrangler,/IMAGE_ASSETS/,'Generated concept imagery must not use the retired IMAGE_ASSETS binding.');
assert.match(wrangler,/CUSTOMER_ASSETS/,'Customer-supplied production imagery must use isolated private storage.');
const directHardening=designWorker.includes("import appWorker from './platform-hardening.js'");
const reliabilityHardening=designWorker.includes("import appWorker from './reliability-hotfix.js'")&&reliabilityWorker.includes("import appWorker from './platform-hardening.js'");
const staleRecoveryHardening=designWorker.includes("import appWorker from './stale-build-recovery.js'")&&((staleRecovery.includes("import appWorker from './reliability-hotfix.js'")&&reliabilityWorker.includes("import appWorker from './platform-hardening.js'"))||(staleRecovery.includes("import appWorker from './customer-assets.js'")&&customerAssets.includes("import baseWorker from './reliability-hotfix.js'")&&reliabilityWorker.includes("import appWorker from './platform-hardening.js'")));
assert.ok(/"main": "\.\/worker\/platform-hardening\.js"/.test(wrangler)||(/"main": "\.\/worker\/concept-design-worker\.js"/.test(wrangler)&&(directHardening||reliabilityHardening||staleRecoveryHardening)),'Platform hardening must remain available in the top-level Worker chain for non-build routes.');

console.log('AI image pipeline invariants passed.');
