import fs from 'node:fs';

const enrichment=fs.readFileSync('worker/prospect-enrichment.js','utf8');
const billing=fs.readFileSync('worker/billing.js','utf8');
const designChat=fs.readFileSync('worker/design-chat.js','utf8');
const designStudio=fs.readFileSync('src/pages/admin/design-studio.astro','utf8');
const prospectPage=fs.readFileSync('src/pages/admin/prospect.astro','utf8');
const hardening=fs.readFileSync('worker/platform-hardening.js','utf8');
const reliability=fs.readFileSync('worker/reliability-hotfix.js','utf8');
const staleRecovery=fs.readFileSync('worker/stale-build-recovery.js','utf8');
const conceptDesign=fs.readFileSync('worker/concept-design-worker.js','utf8');
const sourceRouter=fs.readFileSync('worker/providers/business-data.js','utf8');
const wrangler=fs.readFileSync('wrangler.jsonc','utf8');
const migration=fs.readFileSync('migrations/0010_prospect_enrichment.sql','utf8');
const hardeningMigration=fs.readFileSync('migrations/0014_platform_hardening.sql','utf8');
const visualMigration=fs.readFileSync('migrations/0011_visual_inspiration.sql','utf8');
const designMigration=fs.readFileSync('migrations/0012_design_studio.sql','utf8');

const must=(condition,message)=>{if(!condition)throw new Error(message)};

const enrichmentIsTopLevel=wrangler.includes('"main": "./worker/prospect-enrichment.js"');
const billingWrapsEnrichment=wrangler.includes('"main": "./worker/billing.js"')&&billing.includes("import appWorker from './prospect-enrichment.js'");
const designChatWrapsBilling=wrangler.includes('"main": "./worker/design-chat.js"')&&designChat.includes("import appWorker from './billing.js'")&&billing.includes("import appWorker from './prospect-enrichment.js'");
const hardeningWrapsDesign=wrangler.includes('"main": "./worker/platform-hardening.js"')&&hardening.includes("import appWorker from './design-chat.js'")&&designChat.includes("import appWorker from './billing.js'")&&billing.includes("import appWorker from './prospect-enrichment.js'");
const conceptDesignWrapsHardening=wrangler.includes('"main": "./worker/concept-design-worker.js"')&&conceptDesign.includes("import appWorker from './platform-hardening.js'")&&hardening.includes("import appWorker from './design-chat.js'")&&designChat.includes("import appWorker from './billing.js'")&&billing.includes("import appWorker from './prospect-enrichment.js'");
const conceptDesignWrapsReliability=wrangler.includes('"main": "./worker/concept-design-worker.js"')&&conceptDesign.includes("import appWorker from './reliability-hotfix.js'")&&reliability.includes("import appWorker from './platform-hardening.js'")&&hardening.includes("import appWorker from './design-chat.js'")&&designChat.includes("import appWorker from './billing.js'")&&billing.includes("import appWorker from './prospect-enrichment.js'");
const conceptDesignWrapsStaleRecovery=wrangler.includes('"main": "./worker/concept-design-worker.js"')&&conceptDesign.includes("import appWorker from './stale-build-recovery.js'")&&staleRecovery.includes("import appWorker from './reliability-hotfix.js'")&&reliability.includes("import appWorker from './platform-hardening.js'")&&hardening.includes("import appWorker from './design-chat.js'")&&designChat.includes("import appWorker from './billing.js'")&&billing.includes("import appWorker from './prospect-enrichment.js'");
must(enrichmentIsTopLevel||billingWrapsEnrichment||designChatWrapsBilling||hardeningWrapsDesign||conceptDesignWrapsHardening||conceptDesignWrapsReliability||conceptDesignWrapsStaleRecovery,'Prospect enrichment must remain in the top-level Worker chain.');
must(enrichment.includes("origin:'manual'"),'Manual edits must be recorded in field provenance.');
must(enrichment.includes("'manual_existing'"),'Legacy non-empty values must be protected from research overwrite.');
must(enrichment.includes("origin:'research'"),'Research-populated fields must retain research provenance.');
must(enrichment.includes('protectedSnapshot'),'Research must preserve protected prospect values.');
must(enrichment.includes('enrichFromStoredResearch'),'Completed research must enrich the structured prospect record.');
must(enrichment.includes('business_summary'),'Research summary must be promoted to a structured prospect field.');
must(enrichment.includes('google_rating')&&enrichment.includes('google_review_count'),'Verified Google aggregate data must be eligible for enrichment.');
must(enrichment.includes('verified_services_json'),'Verified services must be persisted on the prospect record.');
must(migration.includes('enrichment_provenance_json'),'Canonical migration must include enrichment provenance.');
must(!enrichment.includes('call_attempts')&&!enrichment.includes('next_follow_up')&&!enrichment.includes('decision_maker_reached'),'Research enrichment must not mutate human sales workflow fields.');
must(enrichment.includes('queueAutoResearchAndBuild'),'New prospect creation must queue the automatic research and concept-build workflow.');
must(enrichment.includes("research_status='Queued'"),'Automatic research must expose a queued state.');
must(enrichment.includes("'Browser Research & Build'"),'New prospects must be handed off to the browser-driven long-running workflow.');
must(!enrichment.includes('context?.waitUntil'),'Research plus concept generation must not run in a Worker waitUntil task that can expire mid-build.');
must(prospectPage.includes('runQueuedAutomation'),'Prospect Details must resume queued new-prospect automation from the active browser session.');
must(prospectPage.includes("/research`,{method:'POST'")&&prospectPage.includes("/build-concept`,{method:'POST'"),'Browser automation must run research before the normal top-level concept build endpoint.');
must(conceptDesign.includes('buildGate'),'Top-level Concept Build must prevent overlapping builds.');
must(conceptDesign.includes("concept_state='Building'")||conceptDesign.includes("concept_state!=='Building'"),'Build gate must understand the Building state.');
must(enrichment.includes('places.googleapis.com/v1/places:searchText'),'Google Places enrichment must remain available when confidence routing calls for it.');
must(enrichment.includes('skipHttpRedirect=true'),'Google Place photos must be transient analysis inputs only.');
must(enrichment.includes('Do not copy, reproduce, trace, crop, embed, or otherwise reuse any source photo'),'Visual analysis must prohibit copying source photos.');
must(staleRecovery.includes("p.concept_state='Building'")&&staleRecovery.includes('STALE_MINUTES=15'),'Interrupted concept builds must self-heal instead of remaining Building forever.');

must(designChat.includes('You are CajunSites Design Studio')&&designChat.includes('You edit ONLY'),'Design Studio must use an explicit website-design-only system boundary.');
must(designChat.includes('Never change CajunSites admin'),'Design Studio must explicitly prohibit admin/platform mutations.');
must(designChat.includes('Never invent services, products, credentials'),'Design Studio must preserve verified business truth.');
must(!designChat.includes("tools:[")&&!designChat.includes('tools: ['),'Design Studio model calls must not expose OpenAI tools.');
must(designChat.includes('const PROFILE_KEYS=')&&designChat.includes('concept_design_model_json')&&designChat.includes("'services_presentation'")&&designChat.includes("'imagery_strategy'"),'Design Studio must use the structured design-model field allowlist.');
must(designChat.includes('normalizeProposal'),'Every AI design proposal must be normalized through the allowlist.');
must(designChat.includes("role='assistant'")&&designChat.includes('proposal_json'),'Only stored assistant proposals may be applied.');
must(designChat.includes("p.research_status!=='Complete'"),'Design Studio must require completed research before applying a design.');
must(designChat.includes('rebuild_required:true'),'Design Studio apply must save directives without invoking the lower Worker build path.');
must(!designChat.includes('const build=await appWorker.fetch(new Request(url.toString()'),'Design Studio must not bypass the top-level Concept Build worker.');
must(designStudio.includes("fetch(`/api/admin/prospects/${id}/build-concept`"),'Design Studio UI must start rebuilds through the public top-level Concept Build endpoint.');
must(designStudio.includes('error_stage')&&designStudio.includes('build_id')&&designStudio.includes('rolled_back'),'Design Studio must preserve actionable rebuild diagnostics.');
must(designMigration.includes('design_chat_messages')&&designMigration.includes('design_directives_json'),'Design Studio must have canonical isolated persistence.');

must(sourceRouter.includes('free_first_confidence_driven'),'Business data sources must use a free-first confidence-driven plan.');
must(sourceRouter.includes('shouldUseGoogleVisuals'),'Paid Google visual lookup must be conditional.');
must(hardening.includes('research_cache'),'Research results must be cached.');
must(hardening.includes('/api/admin/dashboard-summary'),'Dashboard must have a consolidated summary endpoint.');
must(hardening.includes('billing_snapshots'),'Actual billing facts must be synchronized locally.');
must(hardening.includes('provider_usage_events'),'Provider/API usage must be observable.');
must(hardening.includes('platform_jobs'),'Long-running operations must expose job state.');
must(hardeningMigration.includes('research_cache')&&hardeningMigration.includes('billing_snapshots')&&hardeningMigration.includes('provider_usage_events'),'Platform hardening must have a canonical migration.');
must(!wrangler.includes('IMAGE_ASSETS')&&!wrangler.includes('r2_buckets'),'Concept AI imagery must not depend on Cloudflare R2.');

console.log('Prospect enrichment, Design Studio, platform hardening, and stale build recovery invariants passed.');
